"""Owner consent page for the embedded OAuth Authorization Server.

The /authorize endpoint never issues codes on its own: it redirects the
browser to /consent, where the server owner must approve the request with
the OAuth owner code (a dedicated secret generated by the launcher and shown
only on the local machine). Without that code nobody who merely knows the
public tunnel URL can obtain a token, even though Dynamic Client
Registration is open as required by the MCP specification.

Protections: constant-time owner-code comparison; single-use CSRF token bound
to the transaction; no-store and anti-framing headers; the owner code is never
echoed back. Brute-force throttling is deliberately asymmetric — a CORRECT
owner code is always honoured, so wrong-attempt limits can never be used to
lock the legitimate owner out (a denial-of-service on the real owner). Wrong
attempts are capped per authorization transaction and rate-limited globally
with a short self-healing rolling window.
"""
from __future__ import annotations

import html
import time
from urllib.parse import urlsplit

from starlette.requests import Request
from starlette.responses import HTMLResponse, RedirectResponse, Response

from core import _consteq

from .base import SCOPE_DESCRIPTIONS
from .oauth import LocalOAuthProvider, PendingAuthorization

DEFAULT_MAX_ATTEMPTS_PER_TXN = 5
DEFAULT_FAILURE_WINDOW_SECONDS = 60
DEFAULT_MAX_FAILURES_PER_WINDOW = 10

_PAGE_STYLE = """
  :root { color-scheme: light dark; }
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
         max-width: 34rem; margin: 8vh auto; padding: 0 1.25rem; line-height: 1.5; }
  h1 { font-size: 1.25rem; }
  .card { border: 1px solid rgba(128,128,128,.35); border-radius: 10px;
          padding: 1.25rem 1.5rem; }
  dl { display: grid; grid-template-columns: max-content 1fr; gap: .3rem .9rem; }
  dt { opacity: .65; }
  dd { margin: 0; word-break: break-all; }
  ul { padding-left: 1.2rem; }
  li { margin: .25rem 0; }
  code { background: rgba(128,128,128,.15); padding: .1rem .3rem; border-radius: 4px; }
  input[type=password] { width: 100%; padding: .5rem .6rem; margin: .35rem 0 .9rem;
          border: 1px solid rgba(128,128,128,.5); border-radius: 6px; box-sizing: border-box; }
  button { padding: .5rem 1.1rem; border-radius: 6px; border: 1px solid transparent;
           cursor: pointer; font-size: 1rem; }
  .approve { background: #1a7f37; color: #fff; }
  .deny { background: transparent; border-color: rgba(128,128,128,.5); }
  .error { color: #b42929; margin: .5rem 0; }
  .muted { opacity: .65; font-size: .85rem; }
"""


def _security_headers(response: Response, form_action_extra: str = "") -> Response:
    response.headers["Cache-Control"] = "no-store"
    response.headers["X-Frame-Options"] = "DENY"
    form_action = "'self'"
    if form_action_extra:
        form_action = f"'self' {form_action_extra}"
    response.headers["Content-Security-Policy"] = (
        "default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'none'; "
        f"form-action {form_action}"
    )
    response.headers["Referrer-Policy"] = "no-referrer"
    response.headers["X-Content-Type-Options"] = "nosniff"
    return response


def _redirect_origin(redirect_uri: object) -> str:
    """Origin (scheme://host[:port]) of the client redirect URI so the consent
    form CSP form-action can allow the post-approval 302 back to the external
    MCP client. Without it, a 'self'-only form-action silently blocks that
    redirect in real browsers (CSP 3 applies form-action to the resulting
    navigation), and the client never reaches /token."""
    parts = urlsplit(str(redirect_uri))
    if parts.scheme and parts.netloc:
        return f"{parts.scheme}://{parts.netloc}"
    return ""


class ConsentHandler:
    def __init__(
        self,
        provider: LocalOAuthProvider,
        owner_code: str,
        server_name: str,
        server_version: str,
        max_attempts_per_txn: int = DEFAULT_MAX_ATTEMPTS_PER_TXN,
        failure_window_seconds: int = DEFAULT_FAILURE_WINDOW_SECONDS,
        max_failures_per_window: int = DEFAULT_MAX_FAILURES_PER_WINDOW,
    ):
        if not owner_code:
            raise ValueError("OAuth owner code must not be empty")
        self.provider = provider
        self.owner_code = owner_code
        self.server_name = server_name
        self.server_version = server_version
        self.max_attempts_per_txn = max(1, int(max_attempts_per_txn))
        self.failure_window_seconds = max(1, int(failure_window_seconds))
        self.max_failures_per_window = max(1, int(max_failures_per_window))
        self._recent_failures: list[float] = []

    # ------------------------------------------------------------------

    def _check_owner_code(self, candidate: str) -> bool:
        if not candidate:
            return False
        return _consteq(candidate, self.owner_code)

    def _throttled(self) -> bool:
        """True when too many WRONG attempts happened in the rolling window.
        Self-heals as the window slides; only ever gates wrong attempts."""
        cutoff = time.time() - self.failure_window_seconds
        self._recent_failures = [t for t in self._recent_failures if t > cutoff]
        return len(self._recent_failures) >= self.max_failures_per_window

    def _record_failure(self) -> None:
        self._recent_failures.append(time.time())

    # ------------------------------------------------------------------

    async def handle(self, request: Request) -> Response:
        if request.method == "GET":
            txn_id = request.query_params.get("txn", "")
            txn = self.provider.get_txn(txn_id)
            if txn is None:
                return self._expired_page()
            return self._form_page(txn)

        form = await request.form()
        txn_id = str(form.get("txn", ""))
        txn = self.provider.get_txn(txn_id)
        if txn is None:
            return self._expired_page()
        csrf = str(form.get("csrf", ""))
        if not _consteq(csrf, txn.csrf):
            return self._expired_page()

        action = str(form.get("action", ""))
        if action == "deny":
            try:
                target = self.provider.deny_txn(txn_id)
            except KeyError:
                return self._expired_page()
            return _security_headers(RedirectResponse(target, status_code=302))

        # Only an explicit "approve" can grant. Treating "anything but deny" as
        # approval let a forged/garbage action ride a valid owner code into a
        # grant; require the exact action and reject everything else with a 400
        # before any code is minted.
        if action != "approve":
            return self._form_page(txn, error="Invalid action.", status=400)

        # A correct owner code is ALWAYS honoured, before any throttling check,
        # so wrong-attempt limits cannot lock out the legitimate owner.
        if self._check_owner_code(str(form.get("owner_code", ""))):
            try:
                target = self.provider.approve_txn(txn_id)
            except KeyError:
                return self._expired_page()
            return _security_headers(RedirectResponse(target, status_code=302))

        # Wrong code: cap attempts on this transaction and rate-limit wrong
        # attempts globally, without a blanket lockout of the whole handler.
        self._record_failure()
        txn.attempts += 1
        if txn.attempts >= self.max_attempts_per_txn:
            self.provider.invalidate_txn(txn_id)
            return self._form_page(
                txn,
                error=(
                    "Too many incorrect attempts for this request. Start the "
                    "connection again from the MCP client."
                ),
                status=429,
            )
        if self._throttled():
            return self._form_page(
                txn,
                error=(
                    "Too many incorrect attempts right now. Wait a moment and "
                    "try again."
                ),
                status=429,
            )
        return self._form_page(txn, error="Owner code is not valid.", status=403)

    # ------------------------------------------------------------------

    def _expired_page(self) -> Response:
        body = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Authorization request expired</title>
<style>{_PAGE_STYLE}</style></head>
<body><div class="card">
<h1>Authorization request expired</h1>
<p>This authorization request is unknown or has expired.
Return to the MCP client and start the connection again.</p>
</div></body></html>"""
        return _security_headers(HTMLResponse(body, status_code=400))

    def _form_page(
        self, txn: PendingAuthorization, error: str = "", status: int = 200
    ) -> Response:
        client = txn.client
        client_name = html.escape(client.client_name or "(unnamed MCP client)")
        client_id = html.escape(client.client_id)
        redirect_host = html.escape(str(txn.params.redirect_uri))
        scopes = self.provider.granted_scopes(txn)
        scope_items = "\n".join(
            "<li><code>{}</code> — {}</li>".format(
                html.escape(scope), html.escape(SCOPE_DESCRIPTIONS.get(scope, "?"))
            )
            for scope in scopes
        )
        error_html = f'<p class="error">{html.escape(error)}</p>' if error else ""
        body = f"""<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Authorize MCP client</title>
<style>{_PAGE_STYLE}</style></head>
<body>
<div class="card">
<h1>{html.escape(self.server_name)} {html.escape(self.server_version)}</h1>
<p>An MCP client is asking for access to your workspace.</p>
<dl>
  <dt>Client</dt><dd>{client_name}</dd>
  <dt>Client ID</dt><dd>{client_id}</dd>
  <dt>Redirects to</dt><dd>{redirect_host}</dd>
</dl>
<p>Requested access:</p>
<ul>{scope_items}</ul>
{error_html}
<form method="post" action="consent" autocomplete="off">
  <input type="hidden" name="txn" value="{html.escape(txn.txn_id)}">
  <input type="hidden" name="csrf" value="{html.escape(txn.csrf)}">
  <label for="owner_code">OAuth owner code (from SHOW_CONNECTION on the server machine)</label>
  <input type="password" id="owner_code" name="owner_code" autofocus>
  <button class="approve" type="submit" name="action" value="approve">Approve</button>
  <button class="deny" type="submit" name="action" value="deny">Deny</button>
</form>
<p class="muted">Only approve if you started this connection yourself.
The owner code is shown by SHOW_CONNECTION.bat on the machine that runs this server.</p>
</div>
</body></html>"""
        return _security_headers(
            HTMLResponse(body, status_code=status),
            _redirect_origin(txn.params.redirect_uri),
        )
